### ISSUE TITLE
server mode for OBS

### ISSUE THREAD

**Issue by shleeable** [chuabingquan/pxy#1]
I'd love to be able to give to 2+ people a URL to use, that'll stream into my OBS as a source (multiple person panel stream)... person A/B/C all connect with a different stream key to the pxy (server mode) endpoint.

then I just add an SRT/RTSP/RTMP source to my OBS scene with the same streamkey they came in with. Browser -> pxy <- OBS

Obviously latency/quality of service is important... so you'd need to benchmark which protocol from pxy to OBS is best... but if the pxy is hosted on the same box/LAN as OBS. figure it shouldn't matter much

open question: Getting the audio between those people which is a challenge, I'd want everybody to hear each other in sync (could use humble or something)

**Comment by shleeable** [comment]
Sorry. quick research would show SRT has listener mode natively out of the box.. if you feel could support it. Thanks.

https://github.com/openfresh/gosrt

**Comment by chuabingquan** [comment]
Hello @shleeable , the goal of this project (for now) is to serve as a reference implementation for live streams that are proxied between a WebSocket input and an RTMP output. As such, `pxy` would not support SRT. Perhaps this is something that could be explored more in the future, thank you for your suggestion regardless!
